services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=petpalsdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    restart: always
